project_id = "isiweqkdoyxorohuibqb"

[functions.password-recovery]
verify_jwt = true

[functions.email-verification]
verify_jwt = false

[functions.medicines-search]
verify_jwt = true

[functions.analisar-refeicao-ia]
verify_jwt = false
