export const nutritionistDesktopMetrics = [
  {
    id: 'patients',
    label: 'Total pacientes',
    value: '128',
    helper: '+12 novos este mes',
    icon: 'people-outline',
    tone: 'default',
  },
  {
    id: 'risk',
    label: 'Alto risco',
    value: '18',
    helper: '6 pedem contato hoje',
    icon: 'alert-circle-outline',
    tone: 'danger',
  },
  {
    id: 'alerts',
    label: 'Alertas ativos',
    value: '42',
    helper: 'Hiperglicemia, faltas e baixa adesao',
    icon: 'notifications-outline',
    tone: 'warning',
  },
  {
    id: 'adherence',
    label: 'Adesao media',
    value: '84%',
    helper: '+4 p.p. vs semana anterior',
    icon: 'trending-up-outline',
    tone: 'success',
  },
];

export const nutritionistQuickActions = [
  {
    id: 'agenda',
    title: 'Agenda',
    subtitle: '12 consultas entre hoje e amanha',
    helper: 'Abra os atendimentos confirmados e os encaixes do dia.',
    icon: 'calendar-outline',
    route: 'NutricionistaAgenda',
  },
  {
    id: 'mensagens',
    title: 'Mensagens',
    subtitle: '9 nao lidas',
    helper: 'Responda pacientes com duvidas sobre plano e sintomas.',
    icon: 'chatbubbles-outline',
    route: 'NutricionistaMensagens',
  },
  {
    id: 'relatorios',
    title: 'Relatorios',
    subtitle: 'Atualizado hoje as 08:15',
    helper: 'Compare risco, adesao e evolucao da carteira.',
    icon: 'bar-chart-outline',
    route: 'NutricionistaRelatorios',
  },
];

export const nutritionistPatientsMock = [
  {
    id: 'pat-1',
    name: 'Maria Silva',
    age: 45,
    bmi: 31.2,
    risk: 'Alto',
    specialtyTag: 'Diabetes tipo 2',
    objective: 'Emagrecimento',
    adherence: 62,
    alerts: 4,
    unread: 2,
    latestGlucose: 186,
    trendText: 'Subiu 12 mg/dL apos o jantar',
    updatedAt: 'Hoje, 08:40',
    appointmentTime: '09:00',
    notes: 'Pico glicemico recorrente no periodo noturno.',
    goals: [
      { id: 'g1', label: 'Plano alimentar da semana', progress: 72 },
      { id: 'g2', label: 'Registros de glicemia', progress: 58 },
      { id: 'g3', label: 'Hidratacao diaria', progress: 80 },
    ],
    recommendations: ['Caminhada leve apos almoco', 'Fracionar carboidrato noturno', 'Check-in noturno'],
    comorbidities: ['Diabetes tipo 2', 'Hipertensao'],
    medications: ['Metformina 850mg 2x/dia', 'Losartana 50mg'],
    planMeals: [
      {
        id: 'm1',
        time: '07:30',
        title: 'Cafe da manha',
        summary: 'Iogurte natural, chia, banana e aveia.',
      },
      {
        id: 'm2',
        time: '12:30',
        title: 'Almoco',
        summary: 'Arroz integral, feijao, frango grelhado e salada.',
      },
      {
        id: 'm3',
        time: '19:30',
        title: 'Jantar',
        summary: 'Sopa proteica com legumes e torrada integral.',
      },
    ],
    glucose12h: [
      { id: 'g-1', label: '07h', value: 112 },
      { id: 'g-2', label: '09h', value: 124 },
      { id: 'g-3', label: '11h', value: 132 },
      { id: 'g-4', label: '13h', value: 148 },
      { id: 'g-5', label: '15h', value: 154 },
      { id: 'g-6', label: '17h', value: 165 },
      { id: 'g-7', label: '19h', value: 171 },
      { id: 'g-8', label: '21h', value: 186 },
    ],
    personalData: {
      email: 'maria.silva@email.com',
      phone: '(11) 99811-2233',
      city: 'Sao Paulo - SP',
    },
  },
  {
    id: 'pat-2',
    name: 'Joao Santos',
    age: 32,
    bmi: 24.8,
    risk: 'Baixo',
    specialtyTag: 'Reeducacao alimentar',
    objective: 'Reeducacao',
    adherence: 91,
    alerts: 0,
    unread: 0,
    latestGlucose: 104,
    trendText: 'Dentro da meta nas ultimas 24h',
    updatedAt: 'Hoje, 07:55',
    appointmentTime: '10:15',
    notes: 'Boa consistencia no cafe da manha e no sono.',
    goals: [
      { id: 'g1', label: 'Plano alimentar da semana', progress: 93 },
      { id: 'g2', label: 'Registro de refeicoes', progress: 88 },
      { id: 'g3', label: 'Treino e recuperacao', progress: 90 },
    ],
    recommendations: ['Manter rotina de sono', 'Variar legumes no jantar', 'Seguir pre-treino combinado'],
    comorbidities: ['Nenhuma referida'],
    medications: ['Sem uso continuo'],
    planMeals: [
      {
        id: 'm1',
        time: '06:45',
        title: 'Cafe da manha',
        summary: 'Pao integral, ovos mexidos e cafe sem acucar.',
      },
      {
        id: 'm2',
        time: '13:00',
        title: 'Almoco',
        summary: 'Prato equilibrado com proteina magra e vegetais.',
      },
      {
        id: 'm3',
        time: '17:00',
        title: 'Lanche',
        summary: 'Fruta com whey protein e castanhas.',
      },
    ],
    glucose12h: [
      { id: 'g-1', label: '07h', value: 98 },
      { id: 'g-2', label: '09h', value: 101 },
      { id: 'g-3', label: '11h', value: 103 },
      { id: 'g-4', label: '13h', value: 105 },
      { id: 'g-5', label: '15h', value: 108 },
      { id: 'g-6', label: '17h', value: 104 },
      { id: 'g-7', label: '19h', value: 106 },
      { id: 'g-8', label: '21h', value: 104 },
    ],
    personalData: {
      email: 'joao.santos@email.com',
      phone: '(11) 99710-1010',
      city: 'Campinas - SP',
    },
  },
  {
    id: 'pat-3',
    name: 'Ana Costa',
    age: 38,
    bmi: 27.4,
    risk: 'Moderado',
    specialtyTag: 'Emagrecimento com SOP',
    objective: 'Emagrecimento',
    adherence: 78,
    alerts: 2,
    unread: 1,
    latestGlucose: 138,
    trendText: 'Oscilacao leve no fim da tarde',
    updatedAt: 'Hoje, 09:20',
    appointmentTime: '11:30',
    notes: 'Relatou fome aumentada no meio da tarde.',
    goals: [
      { id: 'g1', label: 'Cafe da manha completo', progress: 84 },
      { id: 'g2', label: 'Meta proteica', progress: 71 },
      { id: 'g3', label: 'Passos por dia', progress: 69 },
    ],
    recommendations: ['Ajustar lanche da tarde', 'Reforcar proteina no jantar', 'Manter 2L de agua'],
    comorbidities: ['SOP', 'Resistencia insulinica'],
    medications: ['Inositol', 'Vitamina D'],
    planMeals: [
      {
        id: 'm1',
        time: '08:00',
        title: 'Cafe da manha',
        summary: 'Panqueca de aveia com iogurte e frutas vermelhas.',
      },
      {
        id: 'm2',
        time: '12:45',
        title: 'Almoco',
        summary: 'Quinoa, peixe assado, legumes e folhas.',
      },
      {
        id: 'm3',
        time: '16:30',
        title: 'Lanche',
        summary: 'Queijo minas, maca e canela.',
      },
    ],
    glucose12h: [
      { id: 'g-1', label: '07h', value: 108 },
      { id: 'g-2', label: '09h', value: 115 },
      { id: 'g-3', label: '11h', value: 124 },
      { id: 'g-4', label: '13h', value: 130 },
      { id: 'g-5', label: '15h', value: 142 },
      { id: 'g-6', label: '17h', value: 138 },
      { id: 'g-7', label: '19h', value: 134 },
      { id: 'g-8', label: '21h', value: 128 },
    ],
    personalData: {
      email: 'ana.costa@email.com',
      phone: '(19) 99881-4000',
      city: 'Jundiai - SP',
    },
  },
  {
    id: 'pat-4',
    name: 'Carlos Lima',
    age: 29,
    bmi: 23.6,
    risk: 'Baixo',
    specialtyTag: 'Ganho de massa',
    objective: 'Ganho de Massa',
    adherence: 88,
    alerts: 1,
    unread: 3,
    latestGlucose: 96,
    trendText: 'Sem intercorrencias esta semana',
    updatedAt: 'Ontem, 19:10',
    appointmentTime: '14:00',
    notes: 'Treinando 5x por semana com boa tolerancia digestiva.',
    goals: [
      { id: 'g1', label: 'Proteina diaria', progress: 86 },
      { id: 'g2', label: 'Refeicoes completas', progress: 90 },
      { id: 'g3', label: 'Sono e recuperacao', progress: 78 },
    ],
    recommendations: ['Aumentar carbo no pos-treino', 'Manter ceia proteica', 'Revisar peso semanal'],
    comorbidities: ['Nenhuma referida'],
    medications: ['Creatina 5g'],
    planMeals: [
      {
        id: 'm1',
        time: '07:00',
        title: 'Cafe da manha',
        summary: 'Tapioca com queijo, ovos e vitamina de banana.',
      },
      {
        id: 'm2',
        time: '12:30',
        title: 'Almoco',
        summary: 'Arroz, feijao, carne magra e legumes cozidos.',
      },
      {
        id: 'm3',
        time: '18:00',
        title: 'Pos-treino',
        summary: 'Shake de whey com fruta e pasta de amendoim.',
      },
    ],
    glucose12h: [
      { id: 'g-1', label: '07h', value: 89 },
      { id: 'g-2', label: '09h', value: 92 },
      { id: 'g-3', label: '11h', value: 96 },
      { id: 'g-4', label: '13h', value: 99 },
      { id: 'g-5', label: '15h', value: 101 },
      { id: 'g-6', label: '17h', value: 98 },
      { id: 'g-7', label: '19h', value: 96 },
      { id: 'g-8', label: '21h', value: 95 },
    ],
    personalData: {
      email: 'carlos.lima@email.com',
      phone: '(11) 98800-7777',
      city: 'Santos - SP',
    },
  },
  {
    id: 'pat-5',
    name: 'Fernanda Rocha',
    age: 41,
    bmi: 29.1,
    risk: 'Moderado',
    specialtyTag: 'Prediabetes',
    objective: 'Reeducacao',
    adherence: 74,
    alerts: 3,
    unread: 1,
    latestGlucose: 152,
    trendText: 'Picos no cafe da tarde e jantar',
    updatedAt: 'Hoje, 06:50',
    appointmentTime: '16:30',
    notes: 'Teve duas noites com baixa duracao de sono.',
    goals: [
      { id: 'g1', label: 'Meta glicemica', progress: 66 },
      { id: 'g2', label: 'Lanches planejados', progress: 72 },
      { id: 'g3', label: 'Rotina de sono', progress: 60 },
    ],
    recommendations: ['Trocar biscoito por lanche proteico', 'Revisar fome emocional', 'Checar sono'],
    comorbidities: ['Prediabetes', 'Dislipidemia'],
    medications: ['Omega 3'],
    planMeals: [
      {
        id: 'm1',
        time: '07:15',
        title: 'Cafe da manha',
        summary: 'Pao integral, cottage e mamão com sementes.',
      },
      {
        id: 'm2',
        time: '12:15',
        title: 'Almoco',
        summary: 'Lentilhas, frango desfiado e salada colorida.',
      },
      {
        id: 'm3',
        time: '16:00',
        title: 'Lanche',
        summary: 'Mix de castanhas e iogurte proteico.',
      },
    ],
    glucose12h: [
      { id: 'g-1', label: '07h', value: 120 },
      { id: 'g-2', label: '09h', value: 128 },
      { id: 'g-3', label: '11h', value: 134 },
      { id: 'g-4', label: '13h', value: 140 },
      { id: 'g-5', label: '15h', value: 152 },
      { id: 'g-6', label: '17h', value: 148 },
      { id: 'g-7', label: '19h', value: 146 },
      { id: 'g-8', label: '21h', value: 150 },
    ],
    personalData: {
      email: 'fernanda.rocha@email.com',
      phone: '(11) 99981-4401',
      city: 'Sao Jose dos Campos - SP',
    },
  },
  {
    id: 'pat-6',
    name: 'Rafael Nunes',
    age: 36,
    bmi: 26.8,
    risk: 'Alto',
    specialtyTag: 'Diabetes tipo 1',
    objective: 'Diabetes',
    adherence: 69,
    alerts: 5,
    unread: 4,
    latestGlucose: 214,
    trendText: 'Duas hiperglicemias desde a madrugada',
    updatedAt: 'Hoje, 05:58',
    appointmentTime: '18:00',
    notes: 'Necessita revisar ajuste de bolus e contagem de carboidrato.',
    goals: [
      { id: 'g1', label: 'Contagem de carboidrato', progress: 62 },
      { id: 'g2', label: 'Aplicacoes no horario', progress: 70 },
      { id: 'g3', label: 'Leituras em faixa', progress: 55 },
    ],
    recommendations: ['Revisar bolus no jantar', 'Aumentar monitoramento pos-refeicao', 'Contato hoje'],
    comorbidities: ['Diabetes tipo 1'],
    medications: ['Insulina basal', 'Insulina ultra rapida'],
    planMeals: [
      {
        id: 'm1',
        time: '07:10',
        title: 'Cafe da manha',
        summary: 'Pao integral, queijo branco e cafe sem acucar.',
      },
      {
        id: 'm2',
        time: '12:40',
        title: 'Almoco',
        summary: 'Arroz, feijao, carne e salada com azeite.',
      },
      {
        id: 'm3',
        time: '20:00',
        title: 'Jantar',
        summary: 'Wrap integral com frango e legumes.',
      },
    ],
    glucose12h: [
      { id: 'g-1', label: '07h', value: 176 },
      { id: 'g-2', label: '09h', value: 184 },
      { id: 'g-3', label: '11h', value: 192 },
      { id: 'g-4', label: '13h', value: 205 },
      { id: 'g-5', label: '15h', value: 214 },
      { id: 'g-6', label: '17h', value: 198 },
      { id: 'g-7', label: '19h', value: 190 },
      { id: 'g-8', label: '21h', value: 182 },
    ],
    personalData: {
      email: 'rafael.nunes@email.com',
      phone: '(21) 98877-3300',
      city: 'Rio de Janeiro - RJ',
    },
  },
];

export const nutritionistRecentUpdates = [
  { id: 'u1', patientId: 'pat-1', title: 'Maria preencheu glicemia e jantar', time: '08:40', detail: 'Leitura de 186 mg/dL e feedback de fome noturna.' },
  { id: 'u2', patientId: 'pat-3', title: 'Ana concluiu metas do cafe da manha', time: '09:05', detail: 'Adesao parcial com nota sobre fome na tarde.' },
  { id: 'u3', patientId: 'pat-5', title: 'Fernanda registrou sono e lanche', time: '06:50', detail: 'Sono curto e lanche com melhor distribuicao proteica.' },
  { id: 'u4', patientId: 'pat-2', title: 'Joao enviou check-in pos-treino', time: '07:55', detail: 'Sem sintomas e com boa energia no treino.' },
];

export const nutritionistScheduleSummary = [
  { id: 'today', label: 'Hoje', value: '6 consultas', helper: '4 confirmadas, 2 em espera' },
  { id: 'week', label: 'Esta semana', value: '24 consultas', helper: '8 retornos e 3 encaixes' },
  { id: 'month', label: 'Este mes', value: '88 consultas', helper: 'Taxa de comparecimento de 92%' },
];

export const nutritionistScheduleDays = {
  hoje: [
    {
      id: 'c1',
      patientId: 'pat-1',
      patientName: 'Maria Silva',
      time: '09:00',
      type: 'Retorno clinico',
      status: 'Alto risco',
      mode: 'Google Meet',
    },
    {
      id: 'c2',
      patientId: 'pat-2',
      patientName: 'Joao Santos',
      time: '10:15',
      type: 'Ajuste de plano',
      status: 'Confirmada',
      mode: 'Google Meet',
    },
    {
      id: 'c3',
      patientId: 'pat-3',
      patientName: 'Ana Costa',
      time: '11:30',
      type: 'Check-in de adesao',
      status: 'Moderado',
      mode: 'Video',
    },
    {
      id: 'c4',
      patientId: 'pat-4',
      patientName: 'Carlos Lima',
      time: '14:00',
      type: 'Evolucao de massa magra',
      status: 'Confirmada',
      mode: 'Meet',
    },
  ],
  amanha: [
    {
      id: 'c5',
      patientId: 'pat-5',
      patientName: 'Fernanda Rocha',
      time: '08:30',
      type: 'Revisao de lanches',
      status: 'Moderado',
      mode: 'Google Meet',
    },
    {
      id: 'c6',
      patientId: 'pat-6',
      patientName: 'Rafael Nunes',
      time: '18:00',
      type: 'Urgencia metabolica',
      status: 'Alto risco',
      mode: 'Video',
    },
  ],
};

export const nutritionistMessagesMock = [
  {
    id: 'chat-1',
    patientId: 'pat-1',
    patientName: 'Maria Silva',
    specialtyTag: 'Diabetes tipo 2',
    unread: 2,
    lastMessageAt: '08:46',
    lastMessage: 'Posso trocar o lanche da noite por iogurte proteico?',
    messages: [
      { id: 'm1', from: 'patient', text: 'Bom dia, acordei com a glicose um pouco alta.', time: '08:12' },
      { id: 'm2', from: 'nutri', text: 'Vi aqui no painel. Como foi o jantar de ontem?', time: '08:18' },
      { id: 'm3', from: 'patient', text: 'Comi arroz, feijao e um pouco de sobremesa.', time: '08:33' },
      { id: 'm4', from: 'patient', text: 'Posso trocar o lanche da noite por iogurte proteico?', time: '08:46' },
    ],
  },
  {
    id: 'chat-2',
    patientId: 'pat-3',
    patientName: 'Ana Costa',
    specialtyTag: 'SOP e emagrecimento',
    unread: 1,
    lastMessageAt: '09:02',
    lastMessage: 'Senti mais fome hoje a tarde.',
    messages: [
      { id: 'm1', from: 'patient', text: 'Senti mais fome hoje a tarde.', time: '09:02' },
      { id: 'm2', from: 'nutri', text: 'Vamos reforcar proteina no lanche das 16h.', time: '09:10' },
    ],
  },
  {
    id: 'chat-3',
    patientId: 'pat-6',
    patientName: 'Rafael Nunes',
    specialtyTag: 'Diabetes tipo 1',
    unread: 4,
    lastMessageAt: '06:04',
    lastMessage: 'Tive duas leituras acima de 200 desde a madrugada.',
    messages: [
      { id: 'm1', from: 'patient', text: 'Tive duas leituras acima de 200 desde a madrugada.', time: '05:58' },
      { id: 'm2', from: 'patient', text: 'A ultima agora foi 214.', time: '06:00' },
      { id: 'm3', from: 'patient', text: 'Acha melhor adiantar a consulta?', time: '06:03' },
      { id: 'm4', from: 'nutri', text: 'Sim. Vou te encaixar e revisar o bolus do jantar.', time: '06:04' },
    ],
  },
  {
    id: 'chat-4',
    patientId: 'pat-2',
    patientName: 'Joao Santos',
    specialtyTag: 'Reeducacao alimentar',
    unread: 0,
    lastMessageAt: 'Ontem',
    lastMessage: 'Treino finalizado, energia boa.',
    messages: [
      { id: 'm1', from: 'patient', text: 'Treino finalizado, energia boa.', time: 'Ontem 20:05' },
      { id: 'm2', from: 'nutri', text: 'Perfeito. Mantemos o pre-treino de hoje.', time: 'Ontem 20:20' },
    ],
  },
];

export const nutritionistReportsMock = {
  objectiveDistribution: [
    { id: 'o1', label: 'Diabetes', value: 34 },
    { id: 'o2', label: 'Emagrecimento', value: 42 },
    { id: 'o3', label: 'Ganho Massa', value: 21 },
    { id: 'o4', label: 'Reeducacao', value: 31 },
  ],
  riskDistribution: [
    { id: 'r1', label: 'Alto', value: 18 },
    { id: 'r2', label: 'Moderado', value: 39 },
    { id: 'r3', label: 'Baixo', value: 71 },
  ],
  weeklyAdherence: [
    { id: 'w1', label: 'Sem 1', value: 74 },
    { id: 'w2', label: 'Sem 2', value: 76 },
    { id: 'w3', label: 'Sem 3', value: 79 },
    { id: 'w4', label: 'Sem 4', value: 84 },
    { id: 'w5', label: 'Sem 5', value: 82 },
    { id: 'w6', label: 'Sem 6', value: 86 },
  ],
  ranking: [
    { id: 'rk1', patientName: 'Joao Santos', adherence: 91, streak: '14 dias seguidos' },
    { id: 'rk2', patientName: 'Carlos Lima', adherence: 88, streak: '11 dias seguidos' },
    { id: 'rk3', patientName: 'Ana Costa', adherence: 78, streak: '8 dias seguidos' },
    { id: 'rk4', patientName: 'Fernanda Rocha', adherence: 74, streak: '6 dias seguidos' },
  ],
};

export function getNutritionistPatientById(patientId) {
  return nutritionistPatientsMock.find((item) => item.id === patientId) || null;
}
